# Generated by Django 5.0.6 on 2024-06-16 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('chapter_number', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('subject', models.CharField(default='ES', max_length=100)),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
