# Generated by Django 5.0.6 on 2024-06-21 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='accounts.pdffile')),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
