# Generated by Django 5.0.6 on 2024-06-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pdfview_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfview',
            name='uploaded_by',
        ),
    ]
