# Generated by Django 5.0.6 on 2024-06-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_pdfview_uploaded_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFView',
        ),
    ]
