# Generated by Django 5.0.6 on 2024-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_pdfview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='subject',
            field=models.CharField(default='EMBEDDED SYSTEMS', max_length=100),
        ),
    ]
