# Generated by Django 5.0.6 on 2024-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_pdffile_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
